# Generated by Django 4.2.5 on 2023-10-16 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('line1', models.TextField()),
                ('line2', models.TextField(null=True)),
                ('long', models.IntegerField(null=True)),
                ('lat', models.IntegerField(null=True)),
                ('municipality', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('page_or_ref', models.TextField(null=True)),
                ('confidence', models.IntegerField(choices=[(0, 'low'), (1, 'regular'), (2, 'high')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_type', models.IntegerField(choices=[(0, 'regular'), (1, 'before'), (2, 'after'), (3, 'about'), (4, 'range'), (5, 'span')], default='regular')),
                ('event_type', models.TextField()),
                ('year_start', models.IntegerField(null=True)),
                ('month_start', models.IntegerField(null=True)),
                ('day_start', models.IntegerField(null=True)),
                ('year_end', models.IntegerField(null=True)),
                ('month_end', models.IntegerField(null=True)),
                ('day_end', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('relative_path', models.FilePathField()),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('given_name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('suffix', models.TextField(null=True)),
                ('prefix', models.TextField(null=True)),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('href', models.TextField()),
                ('name', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('author', models.TextField(null=True)),
                ('pubinfo', models.TextField(null=True)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.media')),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('address_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.address')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
                ('urls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('place_type', models.TextField(null=True)),
                ('enclosed_by', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=10, null=True)),
                ('longitude', models.CharField(max_length=10, null=True)),
                ('code', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.address')),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.media')),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'other')], null=True)),
                ('alternate_names', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_alternate', to='gen_rest_api.name')),
                ('birth', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_birth', to='gen_rest_api.event')),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation')),
                ('death', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_death', to='gen_rest_api.event')),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.event')),
                ('families', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='gen_rest_api.family')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.media')),
                ('nick_names', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_nick', to='gen_rest_api.name')),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note')),
                ('parent_families', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_parent', to='gen_rest_api.family')),
                ('primary_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_primary', to='gen_rest_api.name')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='name',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag'),
        ),
        migrations.AddField(
            model_name='media',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_child', to='gen_rest_api.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation'),
        ),
        migrations.AddField(
            model_name='family',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.event'),
        ),
        migrations.AddField(
            model_name='family',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.media'),
        ),
        migrations.AddField(
            model_name='family',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note'),
        ),
        migrations.AddField(
            model_name='family',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_parent1', to='gen_rest_api.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_parent2', to='gen_rest_api.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag'),
        ),
        migrations.AddField(
            model_name='family',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='event',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.media'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.place'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='citation',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.note'),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.source'),
        ),
        migrations.AddField(
            model_name='citation',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tag'),
        ),
        migrations.AddField(
            model_name='citation',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.AddField(
            model_name='address',
            name='citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.citation'),
        ),
        migrations.AddField(
            model_name='address',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree'),
        ),
        migrations.CreateModel(
            name='TreePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_rest_api.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tree', 'user')},
            },
        ),
    ]
