# Generated by Django 4.2.7 on 2023-11-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
        migrations.AddField(
            model_name='media',
            name='blob',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
