site_name: Fig Tree
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - search.suggest
plugins:
  - offline
  - search
  - mkdocstrings
copyright: Copyright &copy; Daniel Perrefort. All rights reserved.