site_name: Fig Tree
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
plugins:
  - offline
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - index.md
  - getting_started.md
  - Technical References:
      - technical_reference/index.md
      - apps:
          - technical_reference/apps/authentication.md
          - technical_reference/apps/data_api.md
          - technical_reference/apps/signup.md
copyright: Copyright &copy; Daniel Perrefort. All rights reserved.