site_name: Fig Tree
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - navigation.sections
plugins:
  - offline
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - index.md
  - Getting Started:
    - getting_started/deployment.md
    - getting_started/configuration.md
  - Technical References:
      - technical_references/overview.md
      - Site Applications:
          - authentication:
            - technical_references/site_applications/authentication/overview.md
            - technical_references/site_applications/authentication/forms.md
            - technical_references/site_applications/authentication/urls.md
            - technical_references/site_applications/authentication/views.md
          - gen_rest_api:
            - technical_references/site_applications/gen_rest_api/overview.md
            - technical_references/site_applications/gen_rest_api/models.md
            - technical_references/site_applications/gen_rest_api/serializers.md
            - technical_references/site_applications/gen_rest_api/urls.md
            - technical_references/site_applications/gen_rest_api/views.md
          - signup:
            - technical_references/site_applications/signup/overview.md
            - technical_references/site_applications/signup/admin.md
            - technical_references/site_applications/signup/forms.md
            - technical_references/site_applications/signup/managers.md
            - technical_references/site_applications/signup/models.md
            - technical_references/site_applications/signup/urls.md
            - technical_references/site_applications/signup/views.md
copyright: Copyright &copy; Daniel Perrefort. All rights reserved.