site_name: Fig Tree
theme:
  name: material
  palette:
    primary: custom
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
extra:
  version:
    provider: mike
extra_css:
  - _css/theme.css
plugins:
  - offline
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Developer Notes:
      - developer_notes/first_time_setup.md
      - developer_notes/running_tests.md
      - developer_notes/building_docs.md
  - Deployment Guide:
    - deployment_guide/configuration.md
    - deployment_guide/docker.md
  - Technical References:
      - technical_references/overview.md
      - technical_references/primary_url_routing.md
      - technical_references/asgi.md
      - Applications Docs:
          - authentication:
            - technical_references/site_applications/authentication/overview.md
            - technical_references/site_applications/authentication/forms.md
            - technical_references/site_applications/authentication/urls.md
            - technical_references/site_applications/authentication/views.md
          - error_pages:
              - technical_references/site_applications/error_pages/overview.md
              - technical_references/site_applications/error_pages/handlers.md
          - gen_rest_api:
            - technical_references/site_applications/gen_data/overview.md
            - technical_references/site_applications/gen_data/models.md
            - technical_references/site_applications/gen_data/serializers.md
            - technical_references/site_applications/gen_data/urls.md
            - technical_references/site_applications/gen_data/views.md
          - signup:
            - technical_references/site_applications/signup/overview.md
            - technical_references/site_applications/signup/admin.md
            - technical_references/site_applications/signup/forms.md
            - technical_references/site_applications/signup/managers.md
            - technical_references/site_applications/signup/models.md
            - technical_references/site_applications/signup/urls.md
            - technical_references/site_applications/signup/views.md
          - family_trees:
            - technical_references/site_applications/family_trees/overview.md
            - technical_references/site_applications/family_trees/urls.md
copyright: Copyright &copy; Daniel Perrefort. All rights reserved.