[tool.poetry]
name = "fig-tree"
version = "0.0.0"
description = "Data management utility for geneological research"
authors = ["Daniel Perrefort"]
readme = "README.md"
packages = [{ include = "fig_tree" }]

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = "^7.3.0"
selenium = "^4.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
