[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fig-tree"
version = "0.0.0"
description = "Data management utility for geneological research"
authors = ["Daniel Perrefort"]
packages = [{ include = "fig_tree" }]

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.4"
django-bootstrap5 = "23.3"
djangorestframework = "3.14.0"
django-widget-tweaks = "1.4.12"
psycopg2-binary = "^2.9.7"
python-dotenv = "1.0.0"

[tool.poetry.scripts]
fig-tree-manage = "fig_tree.manage:main"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = "7.3.0"
selenium = "4.11.2"
