# Generated by Django 4.2.5 on 2023-11-06 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Tree',
            },
        ),
        migrations.CreateModel(
            name='TreePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(10, 'read'), (20, 'private'), (30, 'write'), (40, 'admin')], default='read')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tree', 'user')},
            },
        ),
    ]
