# Generated by Django 4.2.7 on 2023-11-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
