name: Publish Documentation

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        shell: bash
        run: poetry install --with docs

      - name: Configure git
        run: |
          git config --global user.name "Documentation CI"
          git config --global user.email docs@dummy.bot.com

      - name: Set release version
        if: ${{ github.event_name == 'release'}}
        run: |
          DOC_VERSION=${{ github.event.release.tag_name }}
          poetry run mike deploy --push --update-aliases $DOC_VERSION latest
          poetry run mike set-default --push latest

      - name: Set development version
        if: ${{ github.event_name == 'push'}}
        run: poetry run mike deploy --push --update-aliases develop
