name: Test Application

on:
  workflow_dispatch:
  push:

env:
  PYTHON_VERSION: 3.8

jobs:
  discover_apps:
    runs-on: ubuntu-latest
    name: Discover Applications

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Find testable apps
        id: find_tests
        run: |
          # Find application directories containing a 'tests' subdirectory
          test_dirs=$(find fig_tree/apps -type d -name "tests" -exec dirname {} \;)
          echo "::set-output name=test_dirs::$test_dirs"

  unit_tests:
    runs-on: ubuntu-latest
    name: Application Unit Tests
    needs: [ discover_apps ]

    strategy:
      fail-fast: false
      matrix:
        directory: ${{fromJson(needs.find-test-directories.outputs.test_dirs)}}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: |
          pip install poetry
          poetry env use python${{ env.PYTHON_VERSION }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: poetry install --with test

      - name: Test ${{ matrix.app_name }} app
        run: poetry run python fig_tree/manage.py test ${{ matrix.app_name }}

  function_tests:
    runs-on: ubuntu-latest
    name: Site Function Tests

    steps:
      - name: Placeholder
        run: echo "Hello World!"

  report-test-status:
    name: Report Test Status
    if: always()
    needs: [ unit_tests, function_tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Check build status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
